language: node_js
node_js:
   - "7"
branches:
   only:
      - master
before_script:
   - npm install -g @angular/cli
   - npm install -g cordova ionic
script:
   - ionic cordova build browser
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: www
  on:
    branch: master